ARM: mali400: r5p2_rel0: fix build error
Current kernel version doesn't support pm_runtime_active(), so remove
it to fix below build error.

  CC      drivers/gpu/arm/mali400/r5p2_rel0/linux/mali_kernel_linux.o
drivers/gpu/arm/mali400/r5p2_rel0/linux/mali_kernel_linux.c: In function ‘mali_driver_suspend_scheduler’:
drivers/gpu/arm/mali400/r5p2_rel0/linux/mali_kernel_linux.c:594:2: error: implicit declaration of function ‘pm_runtime_active’ [-Wimplicit-function-declaration]

Include pm_runtime.h to fix below build error when CONFIG_PM_RUNTIME is
disabled.

drivers/gpu/arm/mali400/r5p2_rel0/linux/mali_kernel_linux.c: In function ‘mali_driver_suspend_scheduler’:
drivers/gpu/arm/mali400/r5p2_rel0/linux/mali_kernel_linux.c:595:2: error: implicit declaration of function ‘pm_runtime_active’ [-Werror=implicit-function-declaration]
  if (pm_runtime_active(dev))
  ^

Change-Id: I156ad86fd61b54af9e5a50dac5da0900ee2931ef
Signed-off-by: Joonyoung Shim <jy0922.shim@samsung.com>