ARM: mali400: r5p0_rel0: fix build error
  CC      drivers/gpu/arm/mali400/r5p0_rel0/linux/mali_kernel_linux.o
drivers/gpu/arm/mali400/r5p0_rel0/linux/mali_kernel_linux.c: In function ‘mali_driver_suspend_scheduler’:
drivers/gpu/arm/mali400/r5p0_rel0/linux/mali_kernel_linux.c:594:2: error: implicit declaration of function ‘pm_runtime_active’ [-Wimplicit-function-declaration]

Current kernel version doesn't support pm_runtime_active(), so remove
it to avoid build error.

Change-Id: I63d272effd244218850c9afbb5aa76a963dbd89a
Signed-off-by: Joonyoung Shim <jy0922.shim@samsung.com>